select = [
    "E",  # pycodestyle (error)
    "W",  # pycodestyle (warning)
    # TODO: Enable this again
    #"D",  # pydocstyle
    "I",  # isort
    "ANN",  # flake8-annotations
    "DTZ",  # flake8-datetimez
]
ignore = [
    "ANN101",  # missing-type-self
    "ANN401",  # any-type
    "D100",  # undocumented-public-module
    "D101",  # undocumented-public-class
    "D105",  # undocumented-magic-method
    "D106",  # undocumented-public-nested-class
    "D203",  # one-blank-line-before-class
    "D213",  # multi-line-summary-second-line
    # Doesn't work well for Bubbles, because we use the doc commands also
    # for help command output
    "D400",  # ends-in-period
]

exclude = [
    "build",
    "dist",
]

line-length = 100  # Same as black

[per-file-ignores]
"test_*" = [
    "D",  # Disable documentation lints for test files
    "DTZ",  # Disable timezone lints for test files
]
